### PR TITLE
Update unbound_installer_v1.0beta.sh

### PR DESCRIPTION
**Pull request by MartineauUK**
Fix missing 'name: "."' entry when 'Integrate with Stubby option is used'

### CODE REVIEW

**Comment by MartineauUK** [comment]
@dave14305 Not sure what you mean by

"We cannot append config lines to the postconf file. It has to have a script format and use sed or pc_append, etc."

**Comment by dave14305** [comment]
Sorry, I meant in the check_dnsmasq_parms we are appending the server= line to dnsmasq.postconf directly, like it was still dnsmasq.conf.add.

**Comment by MartineauUK** [comment]
@dave14305 Ahh, yes, I see what you mean.

I cloned the existing '**check_dnsmasq_parms()'** with the intention that '**check_dnsmasq_postconf()**' is not concerned about the _adding_ (pc_append) of new directives, but will ultimately check if the following directives exist:

- pc_delete "servers-file" $CONFIG	
- pc_delete "no-negcache" $CONFIG	
- pc_delete "domain-needed" $CONFIG	
- pc_delete "bogus-priv" $CONFIG	
- pc_replace "cache-size=1500" "cache-size=0" $CONFIG

and if they **DON'T**, will add them as-is to the existing '**dnsmasq.postconf**'.
NOTE: If unbound is uninstalled then the changes need to be re

P.S. Thanks for volunteering!.

**Comment by rgnldo** [comment]
The generated unbound.conf file is very large. See if there is a possibility to add adblock as an option in the script.
The dnsmasq.postconf file is generated by the script, but needs permission to change the /etc/dnsmasq.
I manually gave a chmod +x. Working perfectly.

**Comment by MartineauUK** [comment]
v1.06

**Pull request closed without merging**
